config/routes.rb
DCatalogs::Application.routes.draw do
  devise_for :users, :only => [:sessions, :passwords]

  resources :discounts, :only => [:destroy, :create, :update]
  resources :pictures, :only => [:destroy, :create, :update]
  
  resources :pre_sales do
    resources :discounts, :only => [:new, :edit]
    resources :pictures, :only => [:new, :edit]
  end
  
  resources :items do
    resources :discounts, :only => [:new, :edit]
    resources :pictures, :only => [:new, :edit]
  end

  resources :books do
    resources :discounts, :only => [:new, :edit]
    resources :pictures, :only => [:new, :edit]
  end

  resources :music_boxes do
    resources :discounts, :only => [:new, :edit]
  end

  resources :catalogs, :only => [:index]

  resources :users

  root :to => 'welcome#index'

end

app/models/pre_sale.rb
class PreSale < ActiveRecord::Base
  include Shared::Presentators
  
  attr_accessible :date, :description, :event, :price, :reference_id, :quantity
  
  validates_presence_of :date, :description, :event, :price, :reference_id, :quantity
    
  has_many :pictures, :as => :imageable, :dependent => :destroy  
  has_many :discounts, :as => :discountable, :dependent => :destroy
  
  def self.new_with(common_params, date_components)
    PreSale.new(common_params.merge({ date: PreSale.extract_date_from(date_components).utc }))
  end
  
  def update_attributes_with(common_params, date_components)
    self.update_attributes(common_params.merge({ date: PreSale.extract_date_from(date_components).utc }))
  end
  
  def name 
    event
  end
  
  private
  
  def self.extract_date_from(date_components)
    date = Date.strptime(date_components["text"], "%d-%m-%Y")
    Time.new(date.year, date.month, date.day, date_components["hour"], date_components["minute"]).in_time_zone("Mexico City")
  end
end

app/controllers/pre_sales_controller.rb
class PreSalesController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /pre_sales
  # GET /pre_sales.json
  def index
    @pre_sales = PreSale.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pre_sales }
    end
  end

  # GET /pre_sales/1
  # GET /pre_sales/1.json
  def show
    @pre_sale = PreSale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pre_sale }
    end
  end

  # GET /pre_sales/new
  # GET /pre_sales/new.json
  def new
    @pre_sale = PreSale.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pre_sale }
    end
  end

  # GET /pre_sales/1/edit
  def edit
    @pre_sale = PreSale.find(params[:id])
  end

  # POST /pre_sales
  # POST /pre_sales.json
  def create
    @pre_sale = PreSale.new_with(params[:pre_sale], params[:date])

    respond_to do |format|
      if @pre_sale.save
        format.html { redirect_to @pre_sale, notice: I18n.t('app.views.pre_sales.messages.create.success') }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /pre_sales/1
  # PUT /pre_sales/1.json
  def update
    @pre_sale = PreSale.find(params[:id])

    respond_to do |format|
      if @pre_sale.update_attributes_with(params[:pre_sale], params[:date])
        format.html { redirect_to @pre_sale, notice: I18n.t('app.views.pre_sales.messages.update.success') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pre_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pre_sales/1
  # DELETE /pre_sales/1.json
  def destroy
    @pre_sale = PreSale.find(params[:id])
    @pre_sale.destroy

    respond_to do |format|
      format.html { redirect_to pre_sales_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pre_sales_helper.rb
module PreSalesHelper
end

app/views/pre_sales/_form.html.erb
<%= render :partial => 'shared/error', :locals => {:resource => @pre_sale} %>

<%= form_for @pre_sale, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :event, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :event, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
		<%= select_bootstrap_calendar_for(@pre_sale.date) %>
    </div>
  </div>
  <div class="control-group">
    <%= label :hour_minute, t('activerecord.attributes.pre_sale.hour_minute'), :class => 'control-label' %>
    <div class="controls hour-minutes">
			<%= select_time @pre_sale.date %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :rows => 6, :class => 'text_field' %>
    </div>
  </div>
	
	<%= render :partial => 'commons/form_fields', :locals => {:f => f} %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('app.controls.cancel'),
                pre_sales_path, :class => 'btn' %>
  </div>
<% end %>

app/views/pre_sales/edit.html.erb
<%- model_class = PreSale -%>
<div class="big-panel">
	<div class="page-header">
	  <h1><%= t('app.views.pre_sales.edit.title') %></h1>
	</div>
	<%= render :partial => 'form' %>
</div>

app/views/pre_sales/index.html.erb
<%- model_class = PreSale -%>
<div class="big-panel">
	<div class="page-header">
	  <h1><%=t 'app.navbar.sections.pre_sales' %></h1>
	</div>
	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th><%= model_class.human_attribute_name(:id) %></th>
	      <th><%= t('app.attributes.common.reference_id') %></th>
	      <th><%= model_class.human_attribute_name(:event) %></th>
	      <th><%= model_class.human_attribute_name(:date) %></th>
	      <th><%= t('app.attributes.common.price') %></th>
	      <th><%= model_class.human_attribute_name(:description) %></th>
	      <th><%= t('app.attributes.common.created_at') %></th>
	      <th><%= t('app.attributes.common.quantity') %></th>
	
	      <th><%= t('app.navbar.sections.actions') %></th>
	    </tr>
	  </thead>
	  <tbody>
	    <% @pre_sales.each do |pre_sale| %>
	      <tr>
	        <td class="id-details"><%= link_to pre_sale.id, pre_sale_path(pre_sale) %></td>
	        <td><%= pre_sale.reference_id %></td>
	        <td><%= pre_sale.event %></td>
	        <td><%= pre_sale.date.in_time_zone("Mexico City").to_s(:short) %></td>
	        <td>$<%= pre_sale.price %> MXN</td>
	        <td><%= pre_sale.description %></td>
	        <td><%= distance_of_time_in_words_to_now(pre_sale.created_at, true) %></td>
					<td><%= pre_sale.quantity %></td>
	        <td>
	          <%= link_to t('app.controls.edit'),
	                      edit_pre_sale_path(pre_sale), :class => 'btn btn-mini' %>
	          <%= link_to t('app.controls.destroy'),
	                      pre_sale_path(pre_sale),
	                      :method => :delete,
	                      :confirm => t('app.views.pre_sales.dialogs.destroy_confirmation'),
	                      :class => 'btn btn-mini btn-danger' %>
	        </td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>

	<%= link_to t('app.controls.new_f'), new_pre_sale_path, :class => 'btn btn-primary' %>
</div>

app/views/pre_sales/new.html.erb
<%- model_class = PreSale -%>

<div class="big-panel">
	<div class="page-header">
	  <h1><%= t('app.views.pre_sales.new.title') %></h1>
	</div>
	<%= render :partial => 'form' %>
</div>

app/views/pre_sales/show.html.erb
<%- model_class = PreSale -%>
<div class="big-panel admin">
	<div class="page-header">
	  <h1><%= @pre_sale.event %> <span class="uppercased"><%= @pre_sale.date.in_time_zone("Mexico City").to_s(:short) %></span></h1>
		<h3><%= t('activerecord.models.pre_sale') %></h3>
		<div class="pull-right">
			<p class="price">$<%= @pre_sale.price %> MXN</p>
		</div>
	</div>

	<dl class="dl-horizontal">
	  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
	  <dd><%= @pre_sale.description %></dd>
	</dl>
	
	<div class="form-actions">
	  <%= link_to t('app.controls.back'),
	              pre_sales_path, :class => 'btn'  %>
	  <%= link_to t('app.controls.edit'),
	              edit_pre_sale_path(@pre_sale), :class => 'btn' %>
	  <%= link_to t('app.controls.destroy'),
	              pre_sale_path(@pre_sale),
	              :method => 'delete',
	              :confirm => t('app.views.pre_sales.dialogs.destroy_confirmation'),
	              :class => 'btn btn-danger' %>
	</div>
	
	<%= render :partial => 'shared/associated_views', :locals => { :associated_record => @pre_sale } %>
</div>