config/routes.rb
DCatalogs::Application.routes.draw do
  devise_for :users, :only => [:sessions, :passwords]

  resources :discounts, :only => [:destroy, :create, :update]
  resources :pictures, :only => [:destroy, :create, :update]
  
  resources :pre_sales do
    resources :discounts, :only => [:new, :edit]
    resources :pictures, :only => [:new, :edit]
  end
  
  resources :items do
    resources :discounts, :only => [:new, :edit]
    resources :pictures, :only => [:new, :edit]
  end

  resources :books do
    resources :discounts, :only => [:new, :edit]
    resources :pictures, :only => [:new, :edit]
  end

  resources :music_boxes do
    resources :discounts, :only => [:new, :edit]
  end

  resources :catalogs, :only => [:index]

  resources :users

  root :to => 'welcome#index'

end

app/models/music_box.rb
class MusicBox < ActiveRecord::Base
  include Shared::Presentators::CatalogListPreview
  include Shared::Categories
  
  attr_accessible :artist, :presentation_format, :label, :price, :title, :kind, :reference_id, :quantity
  
  has_many :discounts, :as => :discountable, :dependent => :destroy
    
  validates_presence_of :title, :artist, :presentation_format, :price, :kind, :reference_id, :quantity
  
  def humanized_presentation_format
    MusicBox.humanized_category_for(:presentation_formats, self.presentation_format)
  end
  
  def humanized_kind
    MusicBox.humanized_category_for(:kinds, self.kind)
  end
  
  # Presentators for CatalogListPreview
  def first_field
    title
  end
  
  def image_field
  end
  
  private
  def self.presentation_formats
    { 1 => :single, 2 => :double, 3 => :triple, 4 => :boxset}
  end
  
  def self.kinds
    { 1 => :cd, 2 => :vinil}
  end
end

app/controllers/music_boxes_controller.rb
class MusicBoxesController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /music_boxes
  # GET /music_boxes.json
  def index
    @music_boxes = MusicBox.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @music_boxes }
    end
  end

  # GET /music_boxes/1
  # GET /music_boxes/1.json
  def show
    @music_box = MusicBox.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @music_box }
    end
  end

  # GET /music_boxes/new
  # GET /music_boxes/new.json
  def new
    @music_box = MusicBox.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @music_box }
    end
  end

  # GET /music_boxes/1/edit
  def edit
    @music_box = MusicBox.find(params[:id])
  end

  # POST /music_boxes
  # POST /music_boxes.json
  def create
    @music_box = MusicBox.new(params[:music_box])

    respond_to do |format|
      if @music_box.save
        format.html { redirect_to @music_box, notice: I18n.t('app.views.music_boxes.messages.create.success') }
        format.json { render json: @music_box, status: :created, location: @music_box }
      else
        format.html { render action: "new" }
        format.json { render json: @music_box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /music_boxes/1
  # PUT /music_boxes/1.json
  def update
    @music_box = MusicBox.find(params[:id])

    respond_to do |format|
      if @music_box.update_attributes(params[:music_box])
        format.html { redirect_to @music_box, notice: I18n.t('app.views.music_boxes.messages.update.success') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @music_box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /music_boxes/1
  # DELETE /music_boxes/1.json
  def destroy
    @music_box = MusicBox.find(params[:id])
    @music_box.destroy

    respond_to do |format|
      format.html { redirect_to music_boxes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/music_boxes_helper.rb
module MusicBoxesHelper
end

app/views/music_boxes/_form.html.erb
<%= render :partial => 'shared/error', :locals => {:resource => @music_box} %>

<%= form_for @music_box, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :artist, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :artist, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :presentation_format, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:presentation_format, MusicBox.humanized_categories_for(:presentation_formats).invert, { :include_blank => true, :class => 'select_field'}) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :label, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :label, :class => 'text_field' %>
    </div>
  </div>
	
  <div class="control-group">
    <%= f.label :kind, :class => 'control-label' %>
    <div class="controls">
			<%= f.select(:kind, MusicBox.humanized_categories_for(:kinds).invert, { :include_blank => true, :class => 'select_field'}) %>
    </div>
  </div>
	
	<%= render :partial => 'commons/form_fields', :locals => {:f => f} %>

  <div class="form-actions">
    <%= f.submit t('app.views.music_boxes.new.register'), :class => 'btn btn-primary' %>
    <%= link_to t('app.controls.cancel'), music_boxes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/music_boxes/edit.html.erb
<%- model_class = MusicBox -%>
<div class="big-panel">
	<div class="page-header">
	  <h1><%= t('app.views.music_boxes.edit.title') %></h1>
	</div>
	<%= render :partial => 'form' %>
</div>

app/views/music_boxes/index.html.erb
<%- model_class = MusicBox -%>
<div class="big-panel">
	<div class="page-header">
	  <h1><%=t 'app.navbar.sections.music' %></h1>
	</div>
	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th><%= model_class.human_attribute_name(:id) %></th>
	      <th><%= t('app.attributes.common.reference_id') %></th>
	      <th><%= model_class.human_attribute_name(:title) %></th>
	      <th><%= model_class.human_attribute_name(:artist) %></th>
	      <th><%= model_class.human_attribute_name(:format) %></th>
	      <th><%= t('app.attributes.common.price') %></th>
	      <th><%= model_class.human_attribute_name(:label) %></th>
	      <th><%= t('app.attributes.common.created_at') %></th>
	      <th><%= t('app.attributes.common.quantity') %></th>
	
	      <th><%= t('app.navbar.sections.actions') %></th>
	    </tr>
	  </thead>
	  <tbody>
	    <% @music_boxes.each do |music_box| %>
	      <tr>
	        <td class="id-details"><%= link_to music_box.id, music_box_path(music_box) %></td>
					<td><%= music_box.reference_id || "---" %></td>
	        <td><%= music_box.title %></td>
	        <td><%= music_box.artist %></td>
	        <td><%= music_box.humanized_presentation_format %></td>
	        <td>$ <%= music_box.price %> MXN</td>
	        <td><%= music_box.label %></td>
	        <td><%= distance_of_time_in_words_to_now(music_box.created_at, true) %></td>
					<td><%= music_box.quantity %></td>
	        <td>
	          <%= link_to t('app.controls.edit'), edit_music_box_path(music_box), :class => 'btn btn-mini' %>
	          <%= link_to t('app.controls.destroy'), music_box_path(music_box),
	                      :method => :delete,
	                      :confirm => t('app.views.music_boxes.dialogs.destroy_confirmation'),
	                      :class => 'btn btn-mini btn-danger' %>
	        </td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>

	<%= link_to t('app.controls.new'), new_music_box_path, :class => 'btn btn-primary' %>
</div>

app/views/music_boxes/new.html.erb
<%- model_class = MusicBox -%>
<div class="big-panel">
	<div class="page-header">
	  <h1><%= t('app.views.music_boxes.new.title') %></h1>
	</div>
	<%= render :partial => 'form' %>
</div>

app/views/music_boxes/show.html.erb
<%- model_class = MusicBox -%>
<div class="big-panel admin">
	<div class="page-header">
	  <h1><%= @music_box.title %> <span class="uppercased"><%= @music_box.artist %></span></h1>
		<h3><%= @music_box.humanized_kind %></h3>
		<div class="pull-right">
			<p class="price">$ <%= @music_box.price %> MXN</p>
		</div>
	</div>

	<dl class="dl-horizontal">
	  <dt><strong><%= model_class.human_attribute_name(:presentation_format) %>:</strong></dt>
	  <dd><%= @music_box.humanized_presentation_format %></dd>
	  <dt><strong><%= model_class.human_attribute_name(:label) %>:</strong></dt>
	  <dd><%= @music_box.label %></dd>
		<dt><strong><%= t('app.attributes.common.quantity') %>:</strong></dt>
	  <dd>
			<% if @music_box.quantity == 1 %>
				<%= t('app.views.common.show.quantity.one') %>
			<% else %>
				<%= t('app.views.common.show.quantity.other', :number => @music_box.quantity) %>
			<% end %>
		</dd>
		<br>
		<dt><strong><%= t('app.attributes.common.created_at') %>:</strong></dt>
	  <dd><%= distance_of_time_in_words_to_now @music_box.created_at %></dd>
		<dt><strong><%= t('app.attributes.common.updated_at') %>:</strong></dt>
	  <dd><%= distance_of_time_in_words_to_now @music_box.updated_at %></dd>
		<br>
		<dt><strong><%= t('app.attributes.common.reference_id') %>:</strong></dt>
	  <dd><%= @music_box.reference_id %></dd>
	</dl>

	<div class="form-actions">
	  <%= link_to t('app.controls.back'), music_boxes_path, :class => 'btn'  %>
	  <%= link_to t('app.controls.edit'), edit_music_box_path(@music_box), :class => 'btn' %>
	  <%= link_to t('app.controls.destroy'), music_box_path(@music_box),
	              :method => 'delete',
	              :confirm => t('app.views.music_boxes.dialogs.destroy_confirmation'),
	              :class => 'btn btn-danger' %>
	</div>
	
	<%= render :partial => 'shared/associated_views', :locals => { :associated_record => @music_box, :views => [:discounts] } %>
	
</div>