config/routes.rb
DCatalogs::Application.routes.draw do
  devise_for :users, :only => [:sessions, :passwords]

  resources :discounts, :only => [:destroy, :create, :update]
  resources :pictures, :only => [:destroy, :create, :update]
  
  resources :pre_sales do
    resources :discounts, :only => [:new, :edit]
    resources :pictures, :only => [:new, :edit]
  end
  
  resources :items do
    resources :discounts, :only => [:new, :edit]
    resources :pictures, :only => [:new, :edit]
  end

  resources :books do
    resources :discounts, :only => [:new, :edit]
    resources :pictures, :only => [:new, :edit]
  end

  resources :music_boxes do
    resources :discounts, :only => [:new, :edit]
  end

  resources :catalogs, :only => [:index]

  resources :users

  root :to => 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  include Shared::Presentators::CatalogListPreview
  include Shared::Categories
  
  attr_accessible :brand, :model, :price, :kind, :quantity, :reference_id
  
  has_many :pictures, :as => :imageable, :dependent => :destroy  
  has_many :discounts, :as => :discountable, :dependent => :destroy
  
  validates_presence_of :reference_id, :brand, :model, :price, :quantity, :kind
  
  def first_field
    brand
  end
  
  def descriptor_field
    model
  end
  
  def second_field
    humanized_kind
  end
  
  def humanized_kind
    Item.humanized_category_for(:kinds, self.kind)
  end
  
  def self.kinds
    { 1 => :accessory, 2 => :equipment}
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: I18n.t('app.views.items.messages.create.success') }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: I18n.t('app.views.items.messages.update.success') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= render :partial => 'shared/error', :locals => {:resource => @item} %>

<%= form_for @item, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :brand, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :brand, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :model, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :model, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :kind, :class => 'control-label' %>
    <div class="controls">
			<%= f.select(:kind, Item.humanized_categories_for(:kinds).invert, { :include_blank => true, :class => 'select_field'}) %>
    </div>
  </div>

	<%= render :partial => 'commons/form_fields', :locals => {:f => f} %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('app.controls.cancel'),
                items_path, :class => 'btn' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%- model_class = Item -%>
<div class="big-panel">
	<div class="page-header">
	  <h1><%=t('app.views.items.edit.title') %></h1>
	</div>
	<%= render :partial => 'form' %>
</div>

app/views/items/index.html.erb
<%- model_class = Item -%>
<div class="big-panel">
	<div class="page-header">
	  <h1><%= t('app.views.items.index.title') %></h1>
	</div>
	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th><%= model_class.human_attribute_name(:id) %></th>
	      <th><%= t('app.attributes.common.reference_id') %></th>
	      <th><%= model_class.human_attribute_name(:brand) %></th>
	      <th><%= model_class.human_attribute_name(:model) %></th>
	      <th><%= t('app.attributes.common.price') %></th>
	      <th><%= t('app.attributes.common.created_at') %></th>
	      <th><%= t('app.attributes.common.quantity') %></th>
	
	      <th><%= t('app.navbar.sections.actions') %></th>
	    </tr>
	  </thead>
	  <tbody>
	    <% @items.each do |item| %>
	      <tr>
	        <td class="id-details"><%= link_to item.id, item_path(item) %></td>
		      <td><%= item.reference_id %></td>
	        <td><%= item.brand %></td>
	        <td><%= item.model %></td>
	        <td>$ <%= item.price %> MXN</td>
	        <td><%= distance_of_time_in_words_to_now(item.created_at, true) %></td>
	        <td><%= item.quantity %></td>
	        <td>
	          <%= link_to t('app.controls.edit'), edit_item_path(item), :class => 'btn btn-mini' %>
	          <%= link_to t('app.controls.destroy'), item_path(item), :method => :delete,
	                      :confirm => t('app.views.items.dialogs.destroy_confirmation'),
	                      :class => 'btn btn-mini btn-danger' %>
	        </td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>

	<%= link_to t('app.controls.new'), new_item_path, :class => 'btn btn-primary' %>
</div>

app/views/items/new.html.erb
<%- model_class = Item -%>
<div class="big-panel">
	<div class="page-header">
	  <h1><%= t('app.views.items.new.title') %></h1>
	</div>
	<%= render :partial => 'form' %>
</div>

app/views/items/show.html.erb
<%- model_class = Item -%>
<div class="big-panel admin">
	<div class="page-header">
	  <h1><%= @item.brand %> <span class="uppercased"><%= @item.model %></span></h1>
		<h3><%= @item.humanized_kind %></h3>
		<div class="pull-right">
			<p class="price">$ <%= @item.price %> MXN</p>
		</div>
	</div>

	<dl class="dl-horizontal">
		<dt><strong><%= model_class.human_attribute_name(:quantity) %>:</strong></dt>
	  <dd>
			<% if @item.quantity == 1 %>
				<%= t('app.views.common.show.quantity.one') %>
			<% else %>
				<%= t('app.views.common.show.quantity.other', :number => @item.quantity) %>
			<% end %>
		</dd>
		<br>
		<dt><strong><%= model_class.human_attribute_name(:created_at) %>:</strong></dt>
	  <dd><%= distance_of_time_in_words_to_now @item.created_at %></dd>
		<dt><strong><%= model_class.human_attribute_name(:updated_at) %>:</strong></dt>
	  <dd><%= distance_of_time_in_words_to_now @item.updated_at %></dd>
		<br>
		<dt><strong><%= model_class.human_attribute_name(:reference_id) %>:</strong></dt>
	  <dd><%= @item.reference_id %></dd>
	</dl>

	<div class="form-actions">
	  <%= link_to t('app.controls.back'), items_path, :class => 'btn'  %>
	  <%= link_to t('app.controls.edit'), edit_item_path(@item), :class => 'btn' %>
	  <%= link_to t('app.controls.destroy'), item_path(@item),
	              :method => 'delete',
	              :confirm => t('app.views.items.dialogs.destroy_confirmation'),
	              :class => 'btn btn-danger' %>
	</div>
	
	<%= render :partial => 'shared/associated_views', :locals => { :associated_record => @item } %>
	
</div>